version: '3'
services:
  app:
    build:
      context: .
      dockerfile: db/Dockerfile
    command: ["go", "run", "main.go"]
    volumes:
      - .:/workspace/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
